name: Auto‑Merge Dependabot

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Auto‑merge Dependabot PR
        uses: pascalgn/automerge-action@v0.15.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          labels: dependencies
