name: Dependabot Version Bump

on:
  pull_request:
    branches:
      - main
    types:
      - opened
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  dependabot-version-bump:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    name: Bump Version for Dependabot PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get current version
        id: version
        run: echo "CURRENT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Bump patch version
        id: bump
        run: |
          npm version patch --no-git-tag-version --no-commit-hooks
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "Version bumped from $CURRENT_VERSION to $NEW_VERSION"

      - name: Create version bump commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: version bump to $NEW_VERSION [skip ci]"
          git push origin HEAD:refs/pull/${{ github.event.pull_request.number }}/head

      - name: Auto-merge Dependabot PR
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
